---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: web

outputs:
- name: build-output

params:
  TERM: dumb

run:
  path: web/ci/tasks/build-web/task.sh
