---
git-uri: https://github.com/pivotal-bank/quotes-service.git
git-branch: development
cf-api-uri: cf-api-uri
cf-target-url: cf-target-url
cf-skip-ssl: true
cf-username: username
cf-password: password
cf-org: org
cf-space: dev
cf-config-server-uri: https://github.com/pivotal-bank/cf-SpringBootTrader-config
cf-config-server-label: master
cf-db-service: p-mysql
cf-db-service-plan: pre-existing-plan
cf-db-service-name: traderdb
cf-quotes-service-name: quotes-service
cf-quotes-service-host: quotes-service
cf-quotes-service-services: traderdb, discovery-service, circuit-breaker-dashboard, config-server
git-private-key: |
  -----BEGIN RSA PRIVATE KEY-----
  ...
  -----END RSA PRIVATE KEY-----
